#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 16, local_size_y = 16) in;

layout (set = 0, binding = 0) uniform sampler2D gbuffer_position;
layout (set = 0, binding = 1) uniform sampler2D gbuffer_albedo;
layout (set = 0, binding = 2) uniform sampler2D gbuffer_normal;
layout (set = 1, binding = 0, rgba8) uniform writeonly image2D output_image;

void main()
{
    vec4 albedo = texture(gbuffer_position, ivec2(gl_GlobalInvocationID.xy));
    imageStore(output_image, ivec2(gl_GlobalInvocationID.xy), albedo);
}
